name: codbex - Build Application
description: Build application from NPM packages
author: codbex

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
    icon: heart
    color: red

# Define your inputs here.
inputs:
    name:
        description: The application name
        required: true
    tag:
        description: The application tag
        default: latest
    install-dependencies:
        description: Whether to install NPM dependencies
        default: 'true'
    dockerfile-location:
        description: The Dockerfile location
        default: ./
    npmrc:
        description: .npmrc config file content
        required: false
    docker-username:
        description: The Docker Username
    docker-password:
        description: The Docker Password
    docker-organization:
        description: The Docker Organization

runs:
    using: node20
    main: dist/index.js
